# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows, ubuntu]

    runs-on: ${{ matrix.os }}-latest

    steps:

    - name: Set up OS label general case
      run: |
        echo "OS_LABEL=${{ matrix.os }}" >> $GITHUB_ENV

    - name: Set up OS label ubuntu
      run: |
        echo "OS_LABEL=linux" >> $GITHUB_ENV
      if: ${{ matrix.os == 'ubuntu' }}

    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64

    - name: Log Java version
      run: java -version

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew jlinkZip -x test -info

    - uses: actions/upload-artifact@v2
      with:
        name: midi-tuutti-${{ env.OS_LABEL }}.zip
        path: build/image-zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/image-zip/midi-tuutti-${{ env.OS_LABEL }}.zip
